_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: "StandardROIHeadsWithAttr"
    NUM_CLASSES: 1600
    NUM_ATTRIBUTES: 400
    CLASS_EMBEDDING_DIM: 256
    ATTRIBUTE_EMBEDDING_DIM: 512
    ATTRIBUTE_LOSS_TYPE: "softmax"  # or "multiclass"
SOLVER:
    STEPS: (210000, 250000)
    MAX_ITER: 270000
DATASETS:
  TRAIN: ("genome_train",)
  TEST: ("genome_val",)
OUTPUT_DIR: "output/genome_faster_rcnn_attr_R_101_FPN_3x"