_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1600
    NUM_ATTRIBUTES: 400
    CLASS_EMBEDDING_DIM: 256
    ATTRIBUTE_EMBEDDING_DIM: 512
DATASETS:
  TRAIN: ("genome_train",)
  TEST: ("genome_val",)
OUTPUT_DIR: "output/genome_faster_rcnn_attr_R_50_RPN_1x"